### ISSUE TITLE
Rename Parametric outer types

### ISSUE THREAD

**Issue by chrisklus** [phetsims/tandem#101] opened 2019-08-07 19:46 UTC
Options:

```
createPropertyIO
PropertyIOCreator
propertyIOCreator
creatorOfPropertyIO

getPropertyIO
getObservableIO
getNullableIO
nullableIO
```

Lowercase indicates that this is a function, not a type. @zepumph and I like the `get` prefix most, as nothing is being created in most cases (because of caching, to be implemented in #102). And, we think it looks nicer than having a lowercased type name, which has potential to be confusing.

**Comment by zepumph** [comment] 2019-08-08 04:19
The point of this issue is that parametric "outer" types are currently named and cased like types, but really they are functions that take parameters and return IOTypes. This makes for a pleasant looking call site ( `PropertyIO( NullabledIO( BooleanIO ) ) )` ) but it is tremendously difficult to grok.

**Comment by samreid** [comment] 2019-08-08 16:29
Are you thinking we would change how these appear in the PhET-iO types API files?  Would it still appear as `PropertyIO(NullableIO(BooleanIO))` or something else?

**Comment by zepumph** [comment] 2019-08-08 17:03
>Would it still appear as PropertyIO(NullableIO(BooleanIO)) or something else?

My thought would be something else. I agree that the above looks really nice! It is an easy API usage. The problem is that it is an incorrect naming. `PropertyIO` is not an IOType, instead it is a function that takes parameters and returns an IOType. Ideally I want to think of "PropertyIO" as the actual IOType. Such that `createPropertyIO( parametersTypes)` could return a `PropertyIO`.

**Comment by samreid** [comment] 2019-08-08 17:11
> The problem is that it is an incorrect naming. 

Developers dealt with this same problem in C++ templates and Java generics and doubtless other languages--it seems a standard paradigm to instantiate these templates/generics using this uniform syntax: e.g. `new Linked_List<char>();`.  I'm not convinced we should pursue something different that deviates from the well-established pattern.

**Comment by zepumph** [comment] 2019-08-22 19:59
I think that @samreid is right here. For this issue:
- [ ] Rename ParametricTypeIO -> ParametricTypeIOImpl
- [ ] Rename getParametricTypeIO -> ParametricTypeIO
- [ ] Regenerate baselines/types if needed

Any other thoughts? @chrisklus do you want to implement?

**Comment by zepumph** [comment] 2019-09-05 17:07
I think that the rename was good for the code vars, but I don't think the `Impl` should leak into the typeName itself. For example, notice how `PropertyIO`'s typeName is not `PropertyIOImpl.<BooleanIO>`. This is done via the string passed to `phetioInherit`. 

I recommend keeping the var names the same, but changing the following line:

```
    return phetioInherit( ObjectIO, `ParametricTypeImplIO${getDefaultParametricTypeNameSuffix( parameterTypes )}`, ParametricTypeImplIO, {}, {

```

to remove the `Impl` piece.

**Comment by zepumph** [comment] 2019-09-20 00:45
It isn't the greatest solution to have a single letter in an acronym separate these two different items. That said it is a balance of readability and conciseness. I am fine going through with it, but would like to see what @pixelzoom thinks about naming parametric outer types `PropertyIOT`, and the actual IO types would then always be correct. 

Some other Options:
* PropertyIOParametric
* PropertyIOP   -> (parametric)
* PropertyIOT -> (template)
* PropertyIOX -> (IDK, `X` is just an obvious character) 

@pixelzoom does this seem like a good direction to go to disambiguate between parametric out types, and IO Types?

**Comment by pixelzoom** [comment] 2019-09-20 01:05
From the CRC:
> - [ ] Names (types, variables, properties, functions,...) should be sufficiently descriptive and specific, and should avoid non-standard abbreviations. 

"IO" is a standard abbreviation. "IOT" is not, and I'm not wild about the abbreviation approach in general.  `PropertyIOParametric`, or perhaps `PropertyIOTemplate`, conforms to PhET standards,  and is imo more appropriate.

**Comment by pixelzoom** [comment] 2019-09-20 01:06
And yes, +1 for disambiguating and making the IO type name be correct.

**Comment by zepumph** [comment] 2019-09-20 22:09
Alright. Time to crowd source. Options on the table:

* PropertyIOParametric
* PropertyIOTemplate
* *write-in*

Please vote!

**Comment by samreid** [comment] 2019-09-23 15:14
I wrote down those options, our starting point, and a `createPropertyIO` option in context so we can take a look in context:

```js
// @public
this.solutionProperty = new Property( this.solutions[ 0 ], {
  tandem: tandem.createTandem( 'solutionProperty' ),
  phetioType: PropertyIO( BeersLawSolutionIO )
} );

// @public
this.solutionProperty = new Property( this.solutions[ 0 ], {
  tandem: tandem.createTandem( 'solutionProperty' ),
  phetioType: createPropertyIO( BeersLawSolutionIO )
} );

// @public
this.solutionProperty = new Property( this.solutions[ 0 ], {
  tandem: tandem.createTandem( 'solutionProperty' ),
  phetioType: PropertyIOParametric( BeersLawSolutionIO )
} );

// @public
this.solutionProperty = new Property( this.solutions[ 0 ], {
  tandem: tandem.createTandem( 'solutionProperty' ),
  phetioType: PropertyIOTemplate( BeersLawSolutionIO )
} );
```

**Comment by chrisklus** [comment] 2019-09-23 17:18
`PropertyIOTemplate` feels clearest and simplest to me.

**Comment by samreid** [comment] 2019-09-24 14:24
Can we re-evaluate `createPropertyIO` now that we are clearer about this being a type constructor rather than a type which will appear in the API?

**Comment by pixelzoom** [comment] 2019-09-24 16:52
How would `createPropertyIO` work?  In the example above, it looks like a single function that is capable of creating any IO type.

**Comment by samreid** [comment] 2019-09-24 16:54
What is now called `PropertyIO` would be renamed to `createPropertyIO`.  It is a single function declared in PropertyIO.js that creates what is currently called `PropertyIOImpl`, but `PropertyIOImpl` will be renamed to `PropertyIO`

**Comment by pixelzoom** [comment] 2019-09-24 16:55
Oh never mind, I see.  It would be identical to `PropertyIO`, just a different name. 

+1 for using a name that looks like a function, instead of a name that looks like a class.

**Comment by pixelzoom** [comment] 2019-09-24 16:57
> It is a single function declared in PropertyIO.js  ...

If `createPropertyIO` is declared in PropertyIO.js, then what does the `require` statement look like that allows you to use it as `createPropertyIO`?

**Comment by samreid** [comment] 2019-09-24 16:58
We could rename PropertyIO.js to createPropertyIO.js

**Comment by pixelzoom** [comment] 2019-09-24 17:06
Continuing with the `createPropertyIO` name...  What would this become?

`phetioType: DerivedPropertyIO( NullableIO( Vector2IO ) )`

Is it this monstrosity?

`phetioType: createDerivedPropertyIO( createNullableIO( Vector2IO ) )`

**Comment by samreid** [comment] 2019-09-24 17:07
Yes, the code for creating it would be `createDerivedPropertyIO( createNullableIO( Vector2IO ) )` and the concrete type would appear in the API file as `DerivedPropertyIO<NullableIO<Vector2IO>>`

**Comment by pixelzoom** [comment] 2019-09-24 17:09
Sorry, I didn't note my edit in my previous comment.  So which of these is it?

`createDerivedPropertyIO( createNullableIO( Vector2IO ) )`

`createDerivedPropertyIO( createNullableIO( createVector2IO() ) )`

**Comment by samreid** [comment] 2019-09-24 17:10
`createDerivedPropertyIO( createNullableIO( Vector2IO ) )`.  We don't need `createVector2IO()` because `Vector2IO` is already a concrete (nonparametric) type.

**Comment by pixelzoom** [comment] 2019-09-24 17:11
So we're going to have some IO types that are available directly (e.g. `Vector2IO`) and some that are returned by `create*IO` functions?   Can you describe how that is going to work?

**Comment by pixelzoom** [comment] 2019-09-24 17:13
And why not use the same pattern for parametric and non-parametric types? What if `Vector2IO` becomes parametric in the future?

**Comment by samreid** [comment] 2019-09-24 17:19
> And why not use the same pattern for parametric and non-parametric types?

Parametric types take type parameters.  Nonparametric types do not.  So why should they use the same pattern?  Are you saying you want `Vector2IO()` instead of `Vector2IO`?

> So we're going to have some IO types that are available directly (e.g. Vector2IO) and some that are returned by create*IO functions? Can you describe how that is going to work?

That's how it currently works in master.  `PropertyIO` is a parametric type, which is to say it is a function that returns a concrete type which is currently called `PropertyIOImpl`.  We wanted to rename `PropertyIOImpl` to `PropertyIO`, but then we had a name collision with `PropertyIO`.  So we thought about renaming what is now `PropertyIO`. We could keep those the same, but we thought it might be confusing.

**Comment by zepumph** [comment] 2019-09-24 17:52
>What if Vector2IO becomes parametric in the future?

Though possible, that seems very unlikely. We have never converted a non-parametric IO type to parametric before, and most are just data types anyways.

I agree that `create*IO()` is verbose, but I can't tell how much of my dislike is that I'm used to the current form. Here are some more thoughts, just to look at them.


```
phetioType: DerivedPropertyIOTemplate( NullableIOTemplate( Vector2IO ) )

phetioType: createDerivedPropertyIO( createNullableIO( Vector2IO ) )

phetioType: templateDerivedPropertyIO( templateNullableIO( Vector2IO ) )

phetioType: derivedPropertyIO( nullableIO( Vector2IO ) ) // eek! Where lowercase indicated a function that returns the IO Type; just a thought.
```


@pixelzoom in the past week note your following comments:

>And yes, +1 for disambiguating and making the IO type name be correct.

>+1 for using a name that looks like a function, instead of a name that looks like a class.

> And why not use the same pattern for parametric and non-parametric types? What if Vector2IO becomes parametric in the future?

I'm a bit confused about what direction you recommend, before that latest comment (https://github.com/phetsims/tandem/issues/101#issuecomment-534656883) I thought that we were all on board with creating naming such that only actual IO Types end in `*IO` and are named as such. Then outer types/parametric functions/IO type creators etc (how ever we call them) are renamed to signify that they are a function that RETURNS an IO Type. Will you please supply recommendations if you do not feel totally aligned with that vision?

**Comment by pixelzoom** [comment] 2019-09-24 18:04
If you're confused, it's because I'm confused, mostly by the lack of examples that are fleshed out enough to be comprehensible to someone who isn't deeply involved in this.   Those of you on the PhET-iO sub team may be fine with abbreviated examples, explicitly discussing cases like `DerivedPropertyIO<NullableIO<Vector2IO>>`, and assuming that the rest of us know the difference between parametric and non-parametric IO types.  But I'm playing some serious catch-up here.   

So my revised vote:

* +1 for disambiguating and making the IO type name be correct
* +1 for using a name that looks like a function, instead of a name that looks like a class
* don't care about the format of `phetioType` values, because they are all equally ugly

**Comment by zepumph** [comment] 2019-09-26 05:58
This issue is marked for PhET-iO meeting, but it is pretty developer specific. There isn't too much on the agenda tomorrow, so I'm going to add it as a last minute discussion topic to dev meeting. I think it will be most efficient if we can all get on the same page and decide what is best synchronously. 

For anyone just joining the party, we are trying to do a rename to disambiguate between between IO Types (the thing that determines the public api for a PhET-iO element), and the "out type" for parametric IO types, that until now have been named just like IO Types. For example, what is currently `PropertyIO`, is actually a function, which takes a "value IO type" and returns the IO Type, with syntax like `PropertyIO( NumberIO )`. This is bad because although both of these share the same naming conventions, one is an IO type (`NumberIO`), and the other is a function that takes `NumberIO` and returns the IO type: `PropertyIO<NumberIO>`. See eyes above, especially https://github.com/phetsims/tandem/issues/101#issuecomment-534144905 and surrounding comments with "eyes" emojis for some current possibilities for conventions around renaming the "outtype function" (Like PropertyIO/EmitterIO/OberservableArrayIO).

**Comment by pixelzoom** [comment] 2019-09-26 15:19
I think that continued to refer to it as the "out type" (sic) is confusing.  It's a function masquerading as a type by using a name that starts with uppercase.

**Comment by samreid** [comment] 2019-09-26 18:04
The first suggestion from the top of the issue is `createPropertyIO`, does that sound OK?  It's a function that creates a `PropertyIO`

**Comment by zepumph** [comment] 2019-10-17 04:13
usages:
```
createPropertyIO( createNullableIO( NumberIO ) )
createFunctionIO( NumberIO, [ StringIO, createNullableIO( NumberIO ) ] )
createEmitterIO( [ NumberIO, StringIO ] )
createEmunerationIO( new Enumeration( [ 'HI', 'HELLO' ] ) )
```

**Comment by chrisklus** [comment] 2019-10-31 19:23
From 10/31/19 dev meeting:

JB: Since they are cached after being created once, should it instead be called `getPropertyIO`?

We are happy with this!

**Comment by samreid** [comment] 2020-05-29 05:08
It has been a long time since we decided this and I just want to double check that converting parametric types from `MyTypeIO` to `getMyTypeIO` is still our preferred solution.  For instance, I see several occurrences in Natural Selection like:

```js
phetioType: PropertyIO( NullableIO( AlleleIO ) ),

// and
phetioType: PropertyIO( NullableIO( ReferenceIO( BunnyIO ) ) ),
```

and I wanted to see if we still want to go with:

```js
phetioType: getPropertyIO( getNullableIO( AlleleIO ) ),

// and
phetioType: getPropertyIO( getNullableIO( getReferenceIO( getBunnyIO ) ) ),
```

I noticed that in https://github.com/phetsims/tandem/issues/101#issuecomment-534654089 the latter pattern was described as a "monstrosity", so I wanted to see if we are more "used to" the former and want to stick with it?

I don't feel very strongly about this issue but wanted to make sure we are still in agreement before spending time working on it.

**Comment by pixelzoom** [comment] 2020-06-02 16:37
At this point, my vote would be to stick with "the former" (what we've been using) and consider it to be syntactic sugar.   If we change to "the latter" (getters) I think there would be confusion about when to use an IO Type vs a getter (`AlleleIO ` vs `getBunnyIO` in the above example).

**Comment by samreid** [comment] 2020-06-02 18:48
Sounds good, @zepumph and @chrisklus OK to close this issue?

**Comment by chrisklus** [comment] 2020-06-03 16:20
Yes, sounds good to me.

**Comment by zepumph** [comment] 2020-06-03 16:29
@jbphet and I just ran into this while working on States of matter phet io state. We find it very confusing that IO types look the same even when they are parametric functions that return IO Types.  @jbphet can you comment on if you would rather see "getEnumerationIO()"  instead of 'EnumerationIO'? 

I think it would make the distinction clearer, but potentially at the cost of more verbose call sites.

**Comment by pixelzoom** [comment] 2020-06-03 16:48
@zepumph said:
> We find it very confusing that IO types look the same even when they are parametric functions that return IO Types.

If the syntax is the same, why do you need to care?  As I said above:
>  If we change to "the latter" (getters) I think there would be confusion about when to use an IO Type vs a getter (AlleleIO vs getBunnyIO in the above example).

If the syntax is the same, then there's no need to figure out whether its a parametric function or not. Or am I missing something?

**Comment by pixelzoom** [comment] 2020-06-04 19:30
I'm still OK with what we've been doing. If the consensus is to change to getters, go for it.

**Comment by zepumph** [comment] 2020-06-05 00:08
I don't feel strongly either way, but I'm thick into the phet-io world, and could just be used to it. I think it would be helpful to hear from @jbphet before continuing. Please read from https://github.com/phetsims/tandem/issues/101#issuecomment-548530886 and let me know what you would like to do.

**Comment by jbphet** [comment] 2020-06-05 18:19
@pixelzoom said:

> I'm still OK with what we've been doing.

...and @zepumph said:

> I don't feel strongly either way[.]

I'm going to defer to the two of you on this one.  I do find some aspects of the IOTypes a little challenging to get my head around, but @pixelzoom is much more steeped in them right now than I am, and I trust his judgement.

**Comment by pixelzoom** [comment] 2020-06-05 18:49
My opinion is still https://github.com/phetsims/tandem/issues/101#issuecomment-637670389:
> At this point, my vote would be to stick with "the former" (what we've been using) and consider it to be syntactic sugar.   If we change to "the latter" (getters) I think there would be confusion about when to use an IO Type vs a getter (`AlleleIO ` vs `getBunnyIO` in the above example). 

https://github.com/phetsims/tandem/issues/101#issuecomment-639070344:
> I'm still OK with what we've been doing. If the consensus is to change to getters, go for it.

**Comment by zepumph** [comment] 2020-06-05 19:36
@samreid ready to close?

**Comment by samreid** [comment] 2020-06-05 19:41
I skimmed the issue and searched for TODOs referencing this issue.  All seems well, closing.

**Closed by samreid** 2020-06-05 19:41 UTC
Labels: dev:chip-away, dev:phet-io
