### ISSUE TITLE
ReferenceIO instances should be phetioState: false

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#241] opened 2021-05-24 23:47 UTC
I found an unimportant bug where ReferenceIO instances are often stateful, in addition to being used for Data-Type serialization. Basically, there are many ReferenceIO instances that look like this in the state. For example in Natural Selection:

```
    "naturalSelection.global.model.alleles.whiteFurAllele": {
        "phetioID": "naturalSelection.global.model.alleles.whiteFurAllele"
    },
    "naturalSelection.global.model.alleles.brownFurAllele": {
        "phetioID": "naturalSelection.global.model.alleles.brownFurAllele"
    },
    "naturalSelection.global.model.alleles.floppyEarsAllele": {
        "phetioID": "naturalSelection.global.model.alleles.floppyEarsAllele"
    },
    "naturalSelection.global.model.alleles.straightEarsAllele": {
        "phetioID": "naturalSelection.global.model.alleles.straightEarsAllele"
    },
    "naturalSelection.global.model.alleles.shortTeethAllele": {
        "phetioID": "naturalSelection.global.model.alleles.shortTeethAllele"
    },
    "naturalSelection.global.model.alleles.longTeethAllele": {
        "phetioID": "naturalSelection.global.model.alleles.longTeethAllele"
    },
```

Basically this is just fluff, but buggy part is that the state engine IS trying to apply state on it. This is also the case for Dialogs.

I propose:

adding an applyState function in ReferenceIO that asserts false. This helped me catch the Natural Selection problems.

Mark all the phetioState: false instances as necessary to get these sims running again.

Tagging https://github.com/phetsims/phet-io/issues/1774 as that issue is where I discovered this.

**Comment by zepumph** [comment] 2021-05-25 00:23
Alright, these are out of state. It ended up being many less usages that I originally thought it would. Wahoo! @samreid please review. Note the changes in Dialog and Popupable. I think it is good to hard code phetioState values, as it seems outdated to me to have sub Properties take their phetioState from parent Nodes.

**Comment by zepumph** [comment] 2021-05-25 00:27
I merged the ReferenceIO change into stateSchema so that I can continue over in https://github.com/phetsims/phet-io/issues/1774.

**Comment by zepumph** [comment] 2021-05-25 16:41
There is a lot of CT errors that @pixelzoom reported, like:

```

diffusion : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621953726213/phet-io-wrappers/state/?sim=diffusion&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22diffusion%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1621953726213%22%2C%22timestamp%22%3A1621955329924%7D
Uncaught Error: Assertion failed: ReferenceIO is meant to be used as DataType serialization (see fromStateObject
Error: Assertion failed: ReferenceIO is meant to be used as DataType serialization (see fromStateObject
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621953726213/assert/js/assert.js:25:13)
at Object.applyState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621953726213/tandem/js/types/ReferenceIO.js:67:19)
at IOType.applyState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621953726213/tandem/js/types/IOType.js:154:14)
at PhetioStateEngine.setStateForPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621953726213/phet-io/js/PhetioStateEngine.js:428:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621953726213/phet-io/js/PhetioStateEngine.js:328:14
at Array.forEach (<anonymous>)
at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621953726213/phet-io/js/PhetioStateEngine.js:313:22)
at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621953726213/phet-io/js/PhetioStateEngine.js:247:31)
at PhetioStateEngine.setFullState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621953726213/phet-io/js/PhetioStateEngine.js:266:10)
at PhetioEngine.implementation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621953726213/phet-io/js/phetioEngine.js:989:32)
id: Bayes Chrome
Snapshot from 5/25/2021, 8:42:06 AM
```

Assigning myself back

**Comment by zepumph** [comment] 2021-05-25 19:07
I committed more fixes that I found. I'm not sure if there are more, but CT will find them. I also improved the assertion message. I'll check back later this evening to confirm all is fixed, or worst case @samreid can fix a couple as they come up using the above commit as an example.

**Comment by zepumph** [comment] 2021-05-25 21:54
CT found another bug where we were hacking around dynamic element creation issues by making dynamic container elements ReferenceIO types. That wasn't right, but it got them into state enough to trigger creation. Above I created `DynamicMarkerIO` to solve this, and to make things more explicit. This was an issue for the Dialog hierarchy. Now instead of an arbitraty referenceIO serialization, we use something like `"johnTravoltage.general.view.navigationBar.phetButton.phetMenu.aboutDialogCapsule.aboutDialog": {},

This is equally as arbitrary, but is hard coded for this exact case (to mark yourself in the state to be then created as a dynamic element in the downstream sim.



As a summary of the work done in this issue:

* ReferenceIO has been a bit of the wild west, being used in all sorts of ways that it wasn't designed for.
* It should not have applyState called on it.
* Its instances should be phetioState:false
* In some cases (like dialog), it was being used just to get a copy of an instance's phetioID into the state. Instead of that I used a new IOType called DynamicMarkerIO.

@samreid sorry to spring this issue on you and then just leave. I think that CT is mostly cleaned up after the above commits, but only time will tell. Over to you for review.

**Comment by zepumph** [comment] 2021-05-25 21:55
To test that everything is working as expected, the state wrapper is your friend. I used JT and opened the AboutDialog. I also used NS because it has a bunch of custom dialogs that should be saved to the downstream sim via state.

**Comment by pixelzoom** [comment] 2021-05-26 12:45
In commit messages above, DynamicMarkerIO was desribed as a "hack":

> Create DynamicMarkerIO.js instead of using ReferenceIO as a hack to trigger dynamic element creation

So is this really "ready for review", or is a real solution needed?

**Comment by pixelzoom** [comment] 2021-05-26 12:47
About ReferenceIO in https://github.com/phetsims/tandem/issues/241#issuecomment-848291033, @zepumph said:
> * Its instances should be phetioState:false

Why isn't this the default? 
Is there an assertion in ReferenceIO that verifies this requirement?

**Comment by samreid** [comment] 2021-05-26 12:50
Maybe this could be parsed as:

> "Create DynamicMarkerIO.js" instead of "using ReferenceIO as a hack" to trigger dynamic element creation

**Comment by pixelzoom** [comment] 2021-05-27 14:54
Some sims were still failing in CT this morning 5/27/21: concentration, FAMB, molecule-polarity, ...

**Comment by samreid** [comment] 2021-05-28 18:44
> Why isn't this the default?

Most objects should have `phetioState: true` which is codified here: https://github.com/phetsims/tandem/blob/6feaf45b1a4a6b75684b312093ee1ed721fb2bbb/js/TandemConstants.js#L21-L37.  There is a single inheritance hierarchy, so all PhetioObjects inherit this default--there is not a separate hierarchy for objects that will be associated with ReferenceIO.

> Is there an assertion in ReferenceIO that verifies this requirement?

There is a downstream assertion in `ReferenceIO.applyState` and in a moment, I'll commit an upstream assertion that catches the error sooner (tested and confirmed in concentration, which is one failing on CT at the moment).

**Comment by samreid** [comment] 2021-05-28 18:55
After adding the assertion, I followed CT and the reports above to visit sims with this problem, and I changed them to `phetioState: false`.  @pixelzoom can you please review everything since this comment? https://github.com/phetsims/tandem/issues/241#issuecomment-848739073. After review, please reassign to me to monitor CT.

**Comment by samreid** [comment] 2021-05-29 20:52
The assertion added earlier was too specific.  I documented why, and removed it, and will wait for another round of CT to check on things.

**Comment by samreid** [comment] 2021-06-01 23:50
CT seems OK again.  @pixelzoom can you please review everything since this comment? https://github.com/phetsims/tandem/issues/241#issuecomment-848739073.

**Comment by pixelzoom** [comment] 2021-06-07 16:01
I don't see any problems with the commits since https://github.com/phetsims/tandem/issues/241#issuecomment-848739073.  But I predict that forgetting to specify `phetioState: false` for a ReferenceIO subtype this will be a contiual problem.

Closing.

**Closed by pixelzoom** 2021-06-07 16:01 UTC
Labels: dev:phet-io, priority:2-high, status:blocks-publication, status:ready-for-review
